version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/scr/app/node_modules
      - ./:/usr/scr/app
    # environment:
      # - CHOKIDAR_USEPOLLING=true
      # - WATCHPACK_POLLING=true
    stdin_open: true

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/scr/app/node_modules
      - ./:/usr/scr/app
    command: ["npm","run","test"]